services:
  - type: web
    name: library-system-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        # This should be set in the Render dashboard as a secret
        sync: false
      - key: JWT_SECRET
        # This should be set in the Render dashboard as a secret
        sync: false
      - key: CLIENT_URL
        value: https://library-system-frontend.onrender.com
      - key: SOCKET_CORS_ORIGIN
        value: https://library-system-frontend.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: library-system-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://library-system-backend.onrender.com/api
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
